// src/post-detail.jsx
import React from 'react'
import {getPost} from './wp'
import styles from './post-detail.css'

export class PostDetail extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      post: null
    }
  }

  componentDidMount () {
    getPost(this.props.params.postId).then((post) => {
      this.setState({
        post
      })
    })
  }

  render () {
    const {post} = this.state
    if (post == null) {
      return <div />
    }
    return <section className={styles.post}>
      <header className={styles.postHeader}>
        <img className={styles.postAvatar} alt={`${post.author.name}'s avatar`} height='48' width='48' src={post.author.avatar_URL} />
        <h2 className={styles.postTitle} dangerouslySetInnerHTML={{__html: post.title}} />
        <p className={styles.postMeta}>
          By <a className={styles.postAuthor} href={post.author.profile_URL}>{post.author.name}</a> under {Object.keys(post.categories).map((key) => {
            const category = post.categories[key]
            return <a key={key} className={styles.postCategory} href={category.meta.links.self}>{category.name}</a>
          })}
        </p>
      </header>
      <div className={styles.postDescription} dangerouslySetInnerHTML={{__html: post.content}} />
    </section>
  }
}

// src/app/post-detail/post-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router'
import { WpService } from '../wp.service'
import { Post } from '../post'

@Component({
  selector: 'app-post-detail',
  templateUrl: './post-detail.component.html',
  styleUrls: ['./post-detail.component.css']
})
export class PostDetailComponent implements OnInit {
  private post = null

  constructor(private route: ActivatedRoute, private wpService: WpService) {
  }

  ngOnInit() {
    this.route.params.forEach((params) => {
      this.wpService.getPost(params['id'])
        .then((post) => {
          this.post = post
        })
    })
  }
}

<section class="post" *ngIf="post">
  <header class="postHeader">
    <img class="postAvatar" alt="{{post.author.name}}&#x27;s avatar" height="48" width="48" [src]="post.author.avatar_urls['48']">
    <h2 class="postTitle" [innerHtml]="post.title.rendered"></h2>
    <p class="postMeta">
      By <a class="postAuthor" href="{{post.author.link}}">{{post.author.name}}</a> under
      <a class="postCategory" href="{{category.link}}" *ngFor="let category of post.categories">{{category.name}}</a>
    </p>
  </header>
  <div class="postDescription" [innerHtml]="post.content.rendered"></div>
</section>
