// src/app/post-list/post-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router'
import { WpService } from '../wp.service'

@Component({
  selector: 'app-post-list',
  templateUrl: './post-list.component.html',
  styleUrls: ['./post-list.component.css']
})
export class PostListComponent implements OnInit {
  posts = []
  page = 1
  totalPages = 1

  constructor(private route: ActivatedRoute, private wpService: WpService) {
  }

  ngOnInit () {
    this.route.params.forEach((params) => {
      this.page = +params['page'] || 1
      this.wpService.getPosts()
        .then((posts) => {
          this.page = posts.page
          this.totalPages = posts.totalPages
          this.posts = posts.data
        })
    })
  }
}

<div class="posts">
  <h1 class="contentSubhead">Recent Posts</h1>
  <section class="post" *ngFor="let post of posts">
    <header class="postHeader">
      <img class="postAvatar" alt="{{post.author.name}}&#x27;s avatar" height="48" width="48" [src]="post.author.avatar_urls['48']">
      <h2 class="postTitle">
        <a routerLink="/posts/{{post.id}}" [innerHtml]="post.title.rendered"></a>
      </h2>
      <p class="postMeta">
        By <a class="postAuthor" href="{{post.author.link}}">{{post.author.name}}</a> under
        <a class="postCategory" href="{{category.link}}" *ngFor="let category of post.categories">{{category.name}}</a>
      </p>
    </header>
    <div class="postDescription" [innerHtml]="post.excerpt.rendered"></div>
  </section>
  <div class="pagination">
    <div class="pure-menu pure-menu-horizontal">
      <ul>
      </ul>
    </div>
  </div>
</div>

// src/post-list.jsx
import React from 'react'
import {Link} from 'react-router'
import {getPosts} from './wp'
import styles from './post-list.css'

export class PostList extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      posts: []
    }
  }

  componentDidMount () {
    getPosts().then(({posts}) => {
      this.setState({
        posts
      })
    })
  }

  render () {
    const {posts} = this.state
    return <div className={styles.posts}>
      <h1 className={styles.contentSubhead}>Recent Posts</h1>
      {posts.map((post) => {
        return <section key={post.ID} className={styles.post}>
          <header className={styles.postHeader}>
            <img className={styles.postAvatar} alt={`${post.author.name}'s avatar`} height='48' width='48' src={post.author.avatar_URL} />
            <h2 className={styles.postTitle}>
              <Link to={`/posts/${post.ID}`} dangerouslySetInnerHTML={{__html: post.title}} />
            </h2>
            <p className={styles.postMeta}>
              By <a className={styles.postAuthor} href={post.author.profile_URL}>{post.author.name}</a> under {Object.keys(post.categories).map((key) => {
                const category = post.categories[key]
                return <a key={key} className={styles.postCategory} href={category.meta.links.self}>{category.name}</a>
              })}
            </p>
          </header>
          <div className={styles.postDescription} dangerouslySetInnerHTML={{__html: post.excerpt}} />
        </section>
      })}
      <div className={styles.pagination}>
        <div className='pure-menu pure-menu-horizontal'>
          <ul>
            <li />
          </ul>
        </div>
      </div>
    </div>
  }
}
